//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityPulse.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Kopieren {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Kopieren() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivityPulse.Lang.Resources - Kopieren", typeof(Resources___Kopieren).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aqua Breeze ähnelt.
        /// </summary>
        public static string cbiAquaBreeze {
            get {
                return ResourceManager.GetString("cbiAquaBreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blossom Blush ähnelt.
        /// </summary>
        public static string cbiBlossomBlush {
            get {
                return ResourceManager.GetString("cbiBlossomBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string cbiDark {
            get {
                return ResourceManager.GetString("cbiDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Develop ähnelt.
        /// </summary>
        public static string cbiDevelop {
            get {
                return ResourceManager.GetString("cbiDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lavender Lullaby ähnelt.
        /// </summary>
        public static string cbiLavender_Lullaby {
            get {
                return ResourceManager.GetString("cbiLavender Lullaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string cbiLight {
            get {
                return ResourceManager.GetString("cbiLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        public static string cbiMain {
            get {
                return ResourceManager.GetString("cbiMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mossy Magic ähnelt.
        /// </summary>
        public static string cbiMossyMagic {
            get {
                return ResourceManager.GetString("cbiMossyMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sapphire Skies ähnelt.
        /// </summary>
        public static string cbiSapphireSkies {
            get {
                return ResourceManager.GetString("cbiSapphireSkies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silent Storm ähnelt.
        /// </summary>
        public static string cbiSilentStorm {
            get {
                return ResourceManager.GetString("cbiSilentStorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stable ähnelt.
        /// </summary>
        public static string cbiStable {
            get {
                return ResourceManager.GetString("cbiStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        public static string cbiSystem {
            get {
                return ResourceManager.GetString("cbiSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tropical Sunset ähnelt.
        /// </summary>
        public static string cbiTropicalSunset {
            get {
                return ResourceManager.GetString("cbiTropicalSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme ähnelt.
        /// </summary>
        public static string cbTheme {
            get {
                return ResourceManager.GetString("cbTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Channel ähnelt.
        /// </summary>
        public static string cbUpdateChannel {
            get {
                return ResourceManager.GetString("cbUpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ActivityPulse - Keep an eye on your digital rhythm! Record your app and system usage and discover exciting insights\nMore information can be found on the website. ähnelt.
        /// </summary>
        public static string tbAbout {
            get {
                return ResourceManager.GetString("tbAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps ähnelt.
        /// </summary>
        public static string tbApps {
            get {
                return ResourceManager.GetString("tbApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App Version ähnelt.
        /// </summary>
        public static string tbAppVersion {
            get {
                return ResourceManager.GetString("tbAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &gt; Changelog ähnelt.
        /// </summary>
        public static string tbChangelog {
            get {
                return ResourceManager.GetString("tbChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &gt; Feedback &amp; Support ähnelt.
        /// </summary>
        public static string tbFeedback {
            get {
                return ResourceManager.GetString("tbFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback &amp; Support ähnelt.
        /// </summary>
        public static string tbFeedbackSupport {
            get {
                return ResourceManager.GetString("tbFeedbackSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string tbGeneral {
            get {
                return ResourceManager.GetString("tbGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host Version ähnelt.
        /// </summary>
        public static string tbHostVersion {
            get {
                return ResourceManager.GetString("tbHostVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imprint ähnelt.
        /// </summary>
        public static string tbImprint {
            get {
                return ResourceManager.GetString("tbImprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jump to ähnelt.
        /// </summary>
        public static string tbJumpTo {
            get {
                return ResourceManager.GetString("tbJumpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal ähnelt.
        /// </summary>
        public static string tbLegal {
            get {
                return ResourceManager.GetString("tbLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        public static string tbLicense {
            get {
                return ResourceManager.GetString("tbLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This product was provided by Adeptstack. Use only for private purposes, no rental or resale or similar! \nSee license information. \n© Adeptstack, All rights reserved!\n ähnelt.
        /// </summary>
        public static string tbLicenseText {
            get {
                return ResourceManager.GetString("tbLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List ähnelt.
        /// </summary>
        public static string tbList {
            get {
                return ResourceManager.GetString("tbList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die monthly analysis ähnelt.
        /// </summary>
        public static string tbMonthA {
            get {
                return ResourceManager.GetString("tbMonthA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need help? ähnelt.
        /// </summary>
        public static string tbNeedHelp {
            get {
                return ResourceManager.GetString("tbNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operatingsystem ähnelt.
        /// </summary>
        public static string tbOS {
            get {
                return ResourceManager.GetString("tbOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        public static string tbOther {
            get {
                return ResourceManager.GetString("tbOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string tbPrivacy {
            get {
                return ResourceManager.GetString("tbPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processor ähnelt.
        /// </summary>
        public static string tbProcessor {
            get {
                return ResourceManager.GetString("tbProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product Overview ähnelt.
        /// </summary>
        public static string tbProductOverview {
            get {
                return ResourceManager.GetString("tbProductOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM ähnelt.
        /// </summary>
        public static string tbRAM {
            get {
                return ResourceManager.GetString("tbRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threads ähnelt.
        /// </summary>
        public static string tbThreads {
            get {
                return ResourceManager.GetString("tbThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        public static string tbToday {
            get {
                return ResourceManager.GetString("tbToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &gt; Website ähnelt.
        /// </summary>
        public static string tbWebsite {
            get {
                return ResourceManager.GetString("tbWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekly analysis ähnelt.
        /// </summary>
        public static string tbWeekA {
            get {
                return ResourceManager.GetString("tbWeekA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yearly analysis ähnelt.
        /// </summary>
        public static string tbYearA {
            get {
                return ResourceManager.GetString("tbYearA", resourceCulture);
            }
        }
    }
}
